services:
    _defaults:
        autowire: true
        autoconfigure: true

    Phunk\Cms\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/PhunkCmsBundle.php'
